//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 博客
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blog
    {
        public int BlogID { get; set; }
        public string Title { get; set; }
        public string Article { get; set; }
        public string AddTime { get; set; }
        public string AccountID { get; set; }
        public string PlayName { get; set; }
        public string BlogName { get; set; }
        public Nullable<int> ViewNum { get; set; }
        public Nullable<int> CommentNum { get; set; }
    }
}
