//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 博客
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int CommentID { get; set; }
        public string BlogID { get; set; }
        public string CommentDate { get; set; }
        public string Commenter { get; set; }
        public string Article { get; set; }
        public Nullable<int> FloorNum { get; set; }
        public Nullable<int> AgreeNum { get; set; }
        public Nullable<int> DisagreeNum { get; set; }
        public string InRepeater { get; set; }
        public string CategoryID { get; set; }
        public string ContentID { get; set; }
        public string MyEmail { get; set; }
    }
}
